export const GeordiErrorCode = {
  // Input / parse
  E_INPUT_EMPTY: 'GEORDI_E_INPUT_EMPTY',
  E_INPUT_INVALID_JSON: 'GEORDI_E_INPUT_INVALID_JSON',
  E_INPUT_INVALID_SDL: 'GEORDI_E_INPUT_INVALID_SDL',
  E_SCENE_MISSING: 'GEORDI_E_SCENE_MISSING',
  E_SCENE_MULTIPLE: 'GEORDI_E_SCENE_MULTIPLE',
  E_VERSION_UNSUPPORTED: 'GEORDI_E_VERSION_UNSUPPORTED',
  E_DIRECTIVE_UNKNOWN: 'GEORDI_E_DIRECTIVE_UNKNOWN',
  E_DIRECTIVE_ARG_UNKNOWN: 'GEORDI_E_DIRECTIVE_ARG_UNKNOWN',
  E_DIRECTIVE_ARG_INVALID_TYPE: 'GEORDI_E_DIRECTIVE_ARG_INVALID_TYPE',
  E_DIRECTIVE_ARG_MISSING: 'GEORDI_E_DIRECTIVE_ARG_MISSING',

  // Validation
  E_SCENE_DIMENSIONS_INVALID: 'GEORDI_E_SCENE_DIMENSIONS_INVALID',
  E_NODE_KIND_INVALID: 'GEORDI_E_NODE_KIND_INVALID',
  E_NODE_DUPLICATE_ID: 'GEORDI_E_NODE_DUPLICATE_ID',
  E_PARENT_NOT_FOUND: 'GEORDI_E_PARENT_NOT_FOUND',
  E_CYCLE_DETECTED: 'GEORDI_E_CYCLE_DETECTED',
  E_PROP_REQUIRED_MISSING: 'GEORDI_E_PROP_REQUIRED_MISSING',
  E_PROP_INVALID_VALUE: 'GEORDI_E_PROP_INVALID_VALUE',
  E_BIND_TARGET_NOT_FOUND: 'GEORDI_E_BIND_TARGET_NOT_FOUND',
  E_BIND_EXPR_INVALID: 'GEORDI_E_BIND_EXPR_INVALID',
  E_REF_TARGET_NOT_FOUND: 'GEORDI_E_REF_TARGET_NOT_FOUND',

  // Emit / runtime
  E_EMIT_TARGET_UNSUPPORTED: 'GEORDI_E_EMIT_TARGET_UNSUPPORTED',
  E_INTERNAL_INVARIANT: 'GEORDI_E_INTERNAL_INVARIANT',

  // General / cross-phase — applicable from any pipeline stage
  /** Thrown from any phase when a feature gate is not yet implemented (e.g. jsonSchema emit). */
  E_FEATURE_NOT_IMPLEMENTED: 'GEORDI_E_FEATURE_NOT_IMPLEMENTED',

  // Warnings
  W_UNUSED_FIELD: 'GEORDI_W_UNUSED_FIELD',
  W_STYLE_IGNORED_FOR_KIND: 'GEORDI_W_STYLE_IGNORED_FOR_KIND',
  W_PROP_OVERRIDDEN: 'GEORDI_W_PROP_OVERRIDDEN',
  /** @deprecated Use E_FEATURE_NOT_IMPLEMENTED for unimplemented feature gates. */
  W_BINARY_PACK_NOT_IMPLEMENTED: 'GEORDI_W_BINARY_PACK_NOT_IMPLEMENTED',
} as const;

export type GeordiErrorCodeValue = (typeof GeordiErrorCode)[keyof typeof GeordiErrorCode];
